[package]
name = "libretto"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.14.0", features = ["serde_json"] }
axum = "0.8.4"
base64 = "0.22.1"
clap = { version = "4.5.36", features = ["derive", "env"] }
clap-verbosity-flag = "3.0.2"
color-eyre = "0.6.5"
dirs = "6.0.0"
eyeball-im = "0.7.0"
futures = "0.3.31"
futures-util = "0.3.31"
icu = "2.0.0"
jiff = "0.2.15"
listenfd = "1.0.2"
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git", rev="40e3cd3c224b359c312c1f3c55b0d4f7b2be4346", features = ["eyre", "native-tls"], default-features = true}
rand = "0.9.1"
regex = "1.11.1"
reqwest = "0.12.19"
rpassword = "7.4.0"

ruma = {version = "0.12.4", features = ["html-matrix", "html"] } # match rust-sdk

rust-embed = { version = "8.7.2", features = ["axum", "mime-guess", "include-exclude"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { git = "https://github.com/JadedBlueEyes/sqlx.git", branch="jade/update-sqlite", default-features = false, features = ["runtime-tokio", "tls-native-tls", "postgres", "macros", "migrate", "json"] }
strum = { version = "0.27.1" }
strum_macros = "0.27.1"
tokio = { version = "1.45.1", features = ["rt", "signal"] }
tokio-stream = "0.1.17"
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
vite-manifest = "0.1.0"

[features]

# "matrix-sdk/bundled-sqlite",
bundled = ["reqwest/native-tls-vendored"] # jiff timezone database?

[lints.rust]
# still refactoring
dead_code = "allow"
